version: '3.8'

services:
  app:
    container_name: nestjs-app
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/chat-app
      - REDIS_HOST=redis  # Set Redis host to service name
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    container_name: mongo
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    restart: always

volumes:
  mongo-data:
